### ISSUE TITLE
open config/capabilities-drop-list.yml: no such file or directory

### ISSUE THREAD

**Issue by gytisgreitai** [Shopify/kubeaudit#103]
running

`kubeaudit -l -n test all`

I get:

`ERRO[0000] This should not have happened, if you are on kubeaudit master please consider to report: open config/capabilities-drop-list.yml: no such file or directory  KubeType=pod Name=test-775c4c6459-wwjbf Namespace=test`

Installed from master just today
```$ git rev-parse HEAD
3a363010d61aecd9d8c26fe7b26763facb956f97
```

relevant config part for the given pod:

```
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop:
                - all
```
