### ISSUE TITLE
labels don't seem to be working?

### ISSUE THREAD

**Issue by gytisgreitai** [Shopify/kubeaudit#104]
Relevant config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nfs-server
  labels:
    name: test-nfs-server
    kubeaudit.allow.privilegeEscalation: "true"
    kubeaudit.allow.privileged: "true"
    kubeaudit.allow.capability: "true"
    kubeaudit.allow.runAsRoot: "true"
    kubeaudit.allow.readOnlyRootFilesystemFalse: "true"
spec:
  selector:
    matchLabels:
      name: t test-nfs-server
  replicas: 1
  template:
    metadata:
      labels:
        name:  test-nfs-server
        kubeaudit.allow.privilegeEscalation: "true"
        kubeaudit.allow.privileged: "true"
        kubeaudit.allow.capability: "true"
        kubeaudit.allow.runAsRoot: "true"
        kubeaudit.allow.readOnlyRootFilesystemFalse: "true"
```

running 

`kubeaudit -l -v ERROR -n test all`

Gives output:
```
time="2018-07-27T13:19:34+03:00" level=error msg="AllowPrivilegeEscalation not set which allows privilege escalation, please set to false" KubeType=deployment Name=test-nfs-server Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="ReadOnlyRootFilesystem not set which results in a writable rootFS, please set to true" KubeType=deployment Name=test-nfs-server Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="RunAsNonRoot is not set, which results in root user being allowed!" KubeType=deployment Name=test-nfs-server Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="Privileged set to true! Please change it to false!" KubeType=deployment Name=test-nfs-server Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="This should not have happened, if you are on kubeaudit master please consider to report: open config/capabilities-drop-list.yml: no such file or directory" KubeType=deployment Name=test-nfs-server Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="AllowPrivilegeEscalation not set which allows privilege escalation, please set to false" KubeType=pod Name=test-nfs-server-6ff457c44c-zvjfc Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="ReadOnlyRootFilesystem not set which results in a writable rootFS, please set to true" KubeType=pod Name=test-nfs-server-6ff457c44c-zvjfc Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="RunAsNonRoot is not set, which results in root user being allowed!" KubeType=pod Name=test-nfs-server-6ff457c44c-zvjfc Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="Privileged set to true! Please change it to false!" KubeType=pod Name=test-nfs-server-6ff457c44c-zvjfc Namespace=test
time="2018-07-27T13:19:34+03:00" level=error msg="This should not have happened, if you are on kubeaudit master please consider to report: open config/capabilities-drop-list.yml: no such file or directory" KubeType=pod Name=test-nfs-server-6ff457c44c-zvjfc Namespace=test
```

am I missing something?
