### ISSUE TITLE
False positive when all capabilities dropped

### ISSUE THREAD

**Issue by Tmlja1Jldmlu** [Shopify/kubeaudit#110]
Running `kubeaudit caps` returns a lot of `ERRO[0003] Capability not dropped` messages for the pods with the following effective settings:
```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
```
From inside the container everything is clearly OK:
```
grep ^Cap /proc/1/status
CapInh:    0000000000000000
CapPrm:    0000000000000000
CapEff:    0000000000000000
CapBnd:    0000000000000000
CapAmb:    0000000000000000
```
