### ISSUE TITLE
Extra newline generated by autofix on manifest starting with comment after yaml separator

### ISSUE THREAD

**Issue by nschhina** [Shopify/kubeaudit#152]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
Extra newline is generated by Autofix on manifest starting with comment after yaml separator.
##### ENVIRONMENT
* Kubeaudit version: 0.4.1 (branch autofix)
* Kubeaudit install method: -

##### STEPS TO REPRODUCE

Create a manifest file with the following structure
```
---
#This is a comment 3
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: null
spec:
  rules: #This is a comment 1
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /testpath
status:
  loadBalancer: {}
#This is a comment 5
```

run
```
kubeaudit autofix -f /path/to/manifest.yml
```

##### EXPECTED RESULTS

There should not be extra newline after yaml separator

##### ACTUAL RESULTS

changes the file to  
```
---
  
#This is a comment 3
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: null
spec:
  rules: #This is a comment 1
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /testpath
status:
  loadBalancer: {}
#This is a comment 5
```
