### ISSUE TITLE
Network Policy Resource added instead of appending to a current deny-all Network Policy ingress/egress policyTypes

### ISSUE THREAD

**Issue by nschhina** [Shopify/kubeaudit#159]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

##### ENVIRONMENT
* Kubeaudit version: 0.4.1
* Kubeaudit install method: - 

##### STEPS TO REPRODUCE

Network Policy Resource added instead of appending to a current deny-all Network Policy ingress/egress policyTypes

Rune kubeaudit autofix on -

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  creationTimestamp: null
spec: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```

##### EXPECTED RESULTS

Ideally ingress or egress should be appended to the existing default  deny-all policyType list instead of create a completely new resource.
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  creationTimestamp: null
spec: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

##### ACTUAL RESULTS

Another default-deny NetworkPolicy resource for ingress or egress is created.
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  creationTimestamp: null
spec: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
```
