### ISSUE TITLE
Comment Unmarshalling bugged for comments preceding image fields 

### ISSUE THREAD

**Issue by nschhina** [Shopify/kubeaudit#203]
##### ISSUE TYPE
 - [x] Bug Report

# BUG REPORT

##### ENVIRONMENT
* Kubeaudit version: 0.5.3
* Kubeaudit install method: -

##### STEPS TO REPRODUCE

```sh
kubeaudit autofix -f followingfile.yml
```

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fakeDeploymentImg1
  namespace: fakeDeploymentImg
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        apps: fakeImage
      annotations:
        container.apparmor.security.beta.kubernetes.io/fakeContainerImg: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      # This is a comment
      - image: gcr.io/docker-images-directory/apps/
        name: fakeContainerImg
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      automountServiceAccountToken: false
  selector: null
status: {}
```

##### EXPECTED RESULTS

Expected following result-
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fakeDeploymentImg1
  namespace: fakeDeploymentImg
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        apps: fakeImage
      annotations:
        container.apparmor.security.beta.kubernetes.io/fakeContainerImg: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      # This is a comment
      - image: gcr.io/docker-images-directory/apps/
        name: fakeContainerImg
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      automountServiceAccountToken: false
  selector: null
status: {}
```

##### ACTUAL RESULTS
Actual output
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fakeDeploymentImg1
  namespace: fakeDeploymentImg
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        apps: fakeImage
      annotations:
        container.apparmor.security.beta.kubernetes.io/fakeContainerImg: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      - # This is a comment
        image: gcr.io/docker-images-directory/apps/
        name: fakeContainerImg
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      automountServiceAccountToken: false
  selector: null
status: {}
```
