### ISSUE TITLE
Support for CustomResourceDefinition workload

### ISSUE THREAD

**Issue by nschhina** [Shopify/kubeaudit#211]
##### ISSUE TYPE
 - [x] Feature Idea

# BUG REPORT

##### SUMMARY

Kubeaudit doesn't parse `CustomResourceDefinition` workload.

##### ENVIRONMENT
* Kubeaudit version: 0.6.0
* Kubeaudit install method: -

##### STEPS TO REPRODUCE

```sh
kubeaudit all -f followingfile.yml
```
##### EXPECTED RESULTS

kubeaudit should warn unsupported resource `CustomResourceDefinition`

##### ACTUAL RESULTS

Errors out with `Invalid kubernetes workload`

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wgnodes.wormhole.gravitational.io
spec:
  group: wormhole.gravitational.io
  names:
    kind: Wgnode
    plural: wgnodes
  scope: Namespaced
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
