### ISSUE TITLE
Capabilities auditor should drop "all"

### ISSUE THREAD

**Issue by genevieveluyt** [Shopify/kubeaudit#260]
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

# FEATURE IDEA

- [x] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** Currently, the capabilities auditor drops all capabilities which are added by default
ie.
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: myContainer
        securityContext:
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETUID
            - SETPCAP
            - SYS_CHROOT
```
If capabilities from this list are needed, people need to remove them from the drop list and add an override label so that kubeaudit won't generate errors.

Instead, we should drop all capabilities and allow people to add specific capabilities with an override label:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        container.audit.kubernetes.io/myContainer.allow-capability-audit-write: ""
    spec:
      containers:
      - name: myContainer
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - AUDIT_WRITE
```
