### ISSUE TITLE
runAsNonRoot False Positive

### ISSUE THREAD

**Issue by ramesh-ramani** [Shopify/kubeaudit#269]
##### ISSUE TYPE
 - [x] Bug Report

# BUG REPORT

##### SUMMARY
Kubeaudit currently returns False positives for "runAsNonRoot". It shows that the Security Context does not have this set ('RunAsNonRoot is not set in ContainerSecurityContext, which results in root user being allowed!'). Is this because it's looking for "RunAsNonRoot" whereas Security Context has "runAsNonRoot" set on it (Caps on 'r')?

##### ENVIRONMENT
* Kubeaudit version: 0.0.0
* Kubeaudit install method: DIY-BUILD

##### STEPS TO REPRODUCE

General Run of kubeaudit

##### EXPECTED RESULTS

Not see 'RunAsNonRoot is not set in ContainerSecurityContext, which results in root user being allowed!' flagged up as an error

##### ACTUAL RESULTS
```
'RunAsNonRoot is not set in ContainerSecurityContext, which results in root user being allowed!' as the Error output
```

##### ADDITIONAL INFORMATION
Security Context:
```      
        securityContext:
        fsGroup: 64999
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
```

Kubeaudit Report:

```
{'Container': <Redacted>, 'KubeType': 'daemonSet', 'Name': <Redacted>, 'Namespace': <Redacted>, 'level': 'error', 'msg': 'RunAsNonRoot is not set in ContainerSecurityContext, which results in root user being allowed!', 'time': '2020-04-20T14:30:15-07:00'}
```

**Comment by genevieveluyt** [comment]
Hi @ramesh-ramani ,

The check looks for `runAsNonRoot` (with the lowercase 'r'). I realize the error message is misleading. It will be fixed with an upcoming release.

You can confirm this by running kubeaudit on a simple manifest, for example

```
apiVersion: apps/v1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
      - name: fakeContainerPrivileged
        securityContext:
          runAsNonRoot: true
```

Running the `nonroot` check on this has no errors.
```
kubeaudit nonroot -f "manifest.yaml"
```

Are you running kubeaudit on a yaml file? If so, are you able to share that file?
