### ISSUE TITLE
Running Kubeaudit as a Cronjob and Kubeaudit's Contianer image

### ISSUE THREAD

**Issue by secmesh** [Shopify/kubeaudit#277]
##### ISSUE TYPE
 - [x] Bug Report

# BUG REPORT

##### SUMMARY
I don't seem to find a kubernetes manifest file over here. I would like to run Kubeaudit as a Cronjob for example. Is this documented somewhere?

**Comment by genevieveluyt** [comment]
Hi @ramesh-ramani,

We don't currently publish a docker image, but you can make your own as follows:

1. Clone the repo
1. Build kubeaudit: `make`
1. Create a docker image: `docker build . -t kubeaudit`

You can then either push this image to Dockerhub or your own registry and set it as the `image` in the Cronjob template, something like

```yaml
apiVersion: batch/v1beta1
kind: CronJob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: <your_registry>/kubeaudit
            args: ["all"]
```

I'm going to see about publishing an official kubeaudit image.

**Comment by J12934** [comment]
Hi 👋
Tried this out and worked nicely with the docker pull request.

One thing missing from the YAML above is the RBAC config. Without any pointers I've settled on the config listed below. (For a single namespace audit)
Is there a way to reduce the permissions to the actually needed rules from the code? Having a `*` on both apiGroups and resources makes me feel a bit uneasy 😬


```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeaudit
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeaudit
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeaudit
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeaudit
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubeaudit
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kubeaudit
          image: shopify/kubeaudit:v0.11.0
          imagePullPolicy: IfNotPresent
          args:
            - "all"
            - "--namespace"
            - "default"
      serviceAccountName: kubeaudit
```

**Comment by genevieveluyt** [comment]
Hi @J12934 , glad it worked for you! Given the resources kubeaudit currently supports, I believe you'll need these RBAC permissions:

```yaml
rules:
  - apiGroups: [""]
    resources:
      - pods
      - podtemplates
      - replicationcontrollers
      - namespaces
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - statefulsets
      - deployments
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
    verbs: ["get", "list"]
  - apiGroups: ["networking"]
    resources:
      - networkpolicies
    verbs: ["get", "list"]
```

Note that we are planning to add support for more resources that may break your job if you update kubeaudit, specifically

* `serviceaccounts` in the `core` API group
*  `jobs` in the `batch` API group

come to mind.

I haven't had a chance to test this if you wouldn't mind letting me know if it works for you!
