### ISSUE TITLE
Missing `apiVersion` and `kind` information

### ISSUE THREAD

**Issue by allir** [Shopify/kubeaudit#291]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
The output does not show the `apiVersion` or the `kind`

Example:
```
---------------- Results for ---------------

  apiVersion:
  kind:
  metadata:
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard

--------------------------------------------
```

*Note*, it does work in "Manifest mode" by providing `-f some.yaml` but not in "Local Mode".

##### ENVIRONMENT
* Kubeaudit version: 0.11.0
* Kubeaudit install method: Tested both DIY-BUILD & Brew

##### STEPS TO REPRODUCE

Download via brew `brew install kubeaudit` or build from source by running `make build` from repository.

Run any subcommand, for example: `kubeaudit nonroot` or `kubeaudit all`

##### EXPECTED RESULTS

Results list both `apiVersion` and `kind` so I expect that it should be populated with information.

##### ACTUAL RESULTS

`apiVersion and `kind` information is not shown. As per the above exmaple.
