### ISSUE TITLE
Nil pointer dereference when running in manifest mode on 

### ISSUE THREAD

**Issue by mikberg** [Shopify/kubeaudit#300]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY

I get nil pointer dereference errors whenever I use kubeaudit in manifest mode on version >= 0.11. _Works fine on 0.10_.

##### ENVIRONMENT
* Kubeaudit version: 0.11.2, 0.11.1 (on MacOS)
* Kubeaudit install method: Both `brew install kubeaudit` and manual download from Releases page

##### STEPS TO REPRODUCE

Run kubeaudit with any subcommand.

##### ACTUAL RESULTS

```
$ kubeaudit all -f my/manifest.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e5dbfa]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).GetName(...)
        k8s.io/apimachinery@v0.18.3/pkg/apis/meta/v1/meta.go:139
github.com/Shopify/kubeaudit.(*Printer).prettyPrintReport(0xc000377bb8, 0xc0003ea9a0)
        github.com/Shopify/kubeaudit/printer.go:70 +0x77a
github.com/Shopify/kubeaudit.(*Printer).PrintReport(0xc000377bb8, 0xc0003ea9a0)
        github.com/Shopify/kubeaudit/printer.go:61 +0x59
github.com/Shopify/kubeaudit.(*Report).PrintResults(0xc0003ea9a0, 0xc000377c48, 0x1, 0x1)
        github.com/Shopify/kubeaudit/kubeaudit.go:253 +0x85
github.com/Shopify/kubeaudit/cmd/commands.runAudit.func1(0x2ac39e0, 0xc0002491c0, 0x0, 0x2)
        github.com/Shopify/kubeaudit/cmd/commands/root.go:80 +0xfe
github.com/Shopify/kubeaudit/cmd/commands.auditAll(0x2ac39e0, 0xc0002491c0, 0x0, 0x2)
        github.com/Shopify/kubeaudit/cmd/commands/all.go:27 +0x22d
github.com/spf13/cobra.(*Command).execute(0x2ac39e0, 0xc0002491a0, 0x2, 0x2, 0x2ac39e0, 0xc0002491a0)
        github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2ac3740, 0x1008285, 0xc00007e058, 0x0)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
github.com/Shopify/kubeaudit/cmd/commands.Execute()
        github.com/Shopify/kubeaudit/cmd/commands/root.go:43 +0x31
main.main()
        github.com/Shopify/kubeaudit/cmd/main.go:6 +0x25
```

##### ADDITIONAL INFORMATION

0.10 works perfectly

**Comment by genevieveluyt** [comment]
Hi @mikberg , could you please provide the manifest file that you're using?

Could you also try running kubeaudit on one of the manifest files included in the repo and see if you get the same error? For example https://github.com/Shopify/kubeaudit/blob/master/auditors/apparmor/fixtures/apparmor-annotation-missing.yml

**Comment by mikberg** [comment]
@genevieveluyt Your example manifest worked. The manifest file I used was a `v1/Service`, a `apps/v1/Deployment` and a `batch/v1/Job` concatinated together. If I commented out the service and the job, leaving the deployment, then it worked on that file.

Running kubeval on this file with only a Service produces the same error:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: my-service
  type: ClusterIP
```

It also fails with this job:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: my-image
          name: my-job
```
