### ISSUE TITLE
when capabilities list is long, autofix doesn't behave as expected

### ISSUE THREAD

**Issue by dani-santos-code** [Shopify/kubeaudit#306]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### ENVIRONMENT
* Kubeaudit version: v0.11.4
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE

1- Save the following as `example.yaml` 
```yaml

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment
  namespace: capabilities-test
spec:
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
    spec:
      containers:
        - name: container1
          image: scratch
          securityContext:
            capabilities:
              add:
                - BPF
                - AUDIT_READ
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - SYSLOG
                - RAWIO
                - SYS_MODULE
                - NET_BROADCAST
                - IPC_OWNER
                - SYS_PTRACE
                - LEASE
                - BLOCK_SUSPEND
                - WAKE_ALARM
                - AUDIT_CONTROL	
                - SYS_TTY_CONFIG
                - SYS_RESOURCE	
                - SYS_NICE
                - SYS_PACCT
                - SYS_RAWIO	
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
        - name: container2
          image: scratch
          securityContext:
            capabilities:
              add:
                - BPF
                - AUDIT_READ
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - SYSLOG
                - RAWIO
                - SYS_MODULE
                - NET_BROADCAST
                - IPC_OWNER
                - SYS_PTRACE
                - LEASE
                - BLOCK_SUSPEND
                - WAKE_ALARM
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
```

2 - run 
```shell
$ kubeaudit autofix -f example.yaml
```
##### EXPECTED RESULTS
I expected it to be formatted like so:

```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment
  namespace: capabilities-some-allowed-multi-containers-mix-labels
spec:
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
      annotations:
        container.apparmor.security.beta.kubernetes.io/container1: runtime/default
        container.apparmor.security.beta.kubernetes.io/container2: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
        - name: container1
          image: scratch
          securityContext:
            capabilities:
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources: {}
        - name: container2
          image: scratch
          securityContext:
            capabilities:
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources: {}
      automountServiceAccountToken: false
  strategy: {}
```

##### ACTUAL RESULTS

The formatting didn't behave as expected, sending part of the text to the end of the file
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment
  namespace: capabilities-some-allowed-multi-containers-mix-labels
spec:
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
      annotations:
        container.apparmor.security.beta.kubernetes.io/container1: runtime/default
        container.apparmor.security.beta.kubernetes.io/container2: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
        - name: container1
          image: scratch
          securityContext:
            capabilities:
              add:
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - BLOCK_SUSPEND
                - AUDIT_CONTROL
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources: {}
        - name: container2
          image: scratch
          securityContext:
            capabilities:
              add:
                - BLOCK_SUSPEND
                - BLOCK_SUSPEND
              drop:
                - NET_ADMIN
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETGID
                - SETUID
                - SETPCAP
                - SYS_CHROOT
                - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources: {}
      automountServiceAccountToken: false
  strategy: {}
         - SYS_BOOT
                - SYS_TIME
                - SYS_CHROOT

```
