### ISSUE TITLE
False positive 'CapabilityOrSecurityContextMissing'

### ISSUE THREAD

**Issue by alice-vsk** [Shopify/kubeaudit#572]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
We defined securityContext for containers in our deployments, but Kubeaudit still returns an error 'CapabilityOrSecurityContextMissing. Message: Security Context not set'. 

##### ENVIRONMENT
* Kubeaudit version: 0.22.0
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE

Run `kubeaudit all`

##### EXPECTED RESULTS

Not having error 'CapabilityOrSecurityContextMissing. Message: Security Context not set'.

##### ACTUAL RESULTS

```
[error] CapabilityOrSecurityContextMissing
Message: Security Context not set. The Security Context should be specified and all Capabilities should be dropped by setting the Drop list to ALL.

```

##### ADDITIONAL INFORMATION

To debug the problem we also tried to output both pod and deployment as a yaml and run Kubeaudit on that, but still seeing an error. 

SecurityContext in pod:
```
apiVersion: v1
kind: Pod
spec:
  containers:
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 100
      runAsNonRoot: true
      runAsUser: 1000
```
