### ISSUE TITLE
kubeaudit autofix: triple dash issue in multiline string

### ISSUE THREAD

**Issue by til69** [Shopify/kubeaudit#582]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
`---` gets mis-interpreted and is an issue at least in the first occurring multiline string

##### ENVIRONMENT
* Kubeaudit version: 0.22.1
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE
*manifest.yaml*
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline-issue
data:
  k1: |
    ---
    This gets messed up
  k2: |
    --
    This is fine
  k3: |
    -----BEGIN CERTIFICATE-----
    It's an issue in certificates, too...
    -----END CERTIFICATE-----
```

```sh
kubeaudit autofix -f manifest.yaml -o out.yaml
```

##### EXPECTED RESULTS
*out.yaml*
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline-issue
data:
  k1: |
    ---
    This gets messed up
  k2: |
    --
    This is fine
  k3: |
    -----BEGIN CERTIFICATE-----
    It's an issue in certificates, too...
    -----END CERTIFICATE-----
```

##### ACTUAL RESULTS
*out.yaml*
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiline-issue
data:
  k1: ""

    ---
    This gets messed up
  k2: |
    --
    This is fine
  k3: |
    -----BEGIN CERTIFICATE-----
    It's an issue in certificates, too...
    -----END CERTIFICATE-----
```
